### ISSUE TITLE
Allow custom names for docker-composer services

### ISSUE THREAD

**Issue by danielsuguimoto** [fireworkweb/fwd#118]
Some commands/builders use hardcoded docker-compose services names. FWD should be able to adapt its commands to the docker-compose's content. Another situation that FWD can't handle because of this issue is a docker-compose file with more than one database services.

Example: https://github.com/fireworkweb/fwd/blob/eabc3da15644acc756695173a26ceaf017c72aa3/app/Builder/Mysql.php#L13

**Comment by fabriciojs** [comment]
This is something important we should think about, possibly evolving further the .fwd into some JSON or YAML format.

@danielsuguimoto do you have a suggestion on how this should be handled?

cc @dbpolito

**Comment by danielsuguimoto** [comment]
@fabriciojs actually, I haven't thought in a solution for this one. But adding a config/env for the default service name and allowing the user to override the service name through command args could be a good start. What do you think?

**Comment by fabriciojs** [comment]
The new [kool](https://github.com/kool-dev/kool) has no hard-coded reference to service names, keeping it 100% at control for the developer.
