### ISSUE TITLE
Improve node_modules for virtualized environments

### ISSUE THREAD

**Issue by gabrielboliveira** [fireworkweb/fwd#119]
For macOS and Windows, that uses a virtualized Docker, we could improve the volumes to mount the `node_modules` folder as a virtual volume, thus not syncing up the folder outside the container. 

We could achieve with something like this: 

```
-v node_modules:/app/node_modules:cached
```

But this maps as root, even if using `AS_USER`, so we need to find the proper fix

**Comment by fabriciojs** [comment]
The bad thing about this would be not being able to see and navigate through node_modules files, in case needed.

Do we think that is acceptable and worth? Maybe we could this as a toggle so people could set it to improve performance if needed?

**Comment by fabriciojs** [comment]
@dbpolito @gabrielboliveira what do you guys think?
