### ISSUE TITLE
Allow usage of composer without start

### ISSUE THREAD

**Issue by gabrielboliveira** [fireworkweb/fwd#129]
We should be able to run "composer" commands even if the services are not running. 

Perhaps we could add a check if the app service is running, otherwise just execute a docker run.

**Comment by fabriciojs** [comment]
@dbpolito worked on something for this effect on the `fwd run` PR. Not sure the status of that though.

**Comment by dbpolito** [comment]
yes, right now you can do something like:

```
fwd run fireworkweb/php:7.4 composer install
```

I started thinking on checking and doing something magic, but not sure if worth it

**Comment by dbpolito** [comment]
What i think would be good is having some aliases for the run command, so we could do something like:

```
fwd run php-7.4 composer install
fwd run php-qa bla
...etc
```

**Comment by fabriciojs** [comment]
@dbpolito  I guess we can conditionally change the wrapper on Composer command, can't we? To change between DockerComposeExec and DockerRun based on StatusTask output?
