### ISSUE TITLE
Create comprehensive README

### ISSUE THREAD

**Issue by gabrielboliveira** [fireworkweb/fwd#13]
- [ ] Create a README with explanation on relevant topics

- what this project is about
- how to get started
- any other relevant topic

**Comment by fabriciojs** [comment]
@felipanico I am assigning this one to you due to your open PR.

**Comment by fabriciojs** [comment]
Let's use as example spatie's proposed README structure:

https://github.com/spatie/skeleton-php#very-short-description-of-the-package
