### ISSUE TITLE
How to set FWD_VERBOSE=1 to all my projects?

### ISSUE THREAD

**Issue by fabriciojs** [fireworkweb/fwd#137]
I would really like to be able to set FWD_VERBOSE=1 for all my projects since I prefer it all verbose!

**Comment by gabrielboliveira** [comment]
You can create a `.fwd` file on your `$HOME` with any variables you want to customize from default. It will first load the default fwd configs, and then read the files in order, overriding any config you may have changed:

- default configs ([.fwd](https://github.com/fireworkweb/fwd/blob/master/.fwd)) (least significant)
- `$HOME/.fwd`
- `.fwd` on current directory
- `.env` on current directory (most significant)

https://github.com/fireworkweb/fwd/blob/32f9ac5c8f3bf4ed88c47dc4602fb3a222d29afe/app/Environment.php#L94-L101

**Comment by fabriciojs** [comment]
Ah, I see - the README also states that: https://github.com/fireworkweb/fwd#environment-variables

![image](https://user-images.githubusercontent.com/1116377/82843768-989dc600-9eb4-11ea-8728-d68df8feb46f.png)

**Comment by carlbastos** [comment]
Reminder to myself: add `.fwd` to `.gitignore`.

**Comment by gabrielboliveira** [comment]
@carlbastos Well, no always you want to ignore the `.fwd`. Perhaps you want to save some project-specific changes, for example PHP version on the `FWD_IMAGE_APP` variable, or node on the `FWD_IMAGE_NODE`.
