### ISSUE TITLE
fwd start não inicia com uma versão mais recente de docker

### ISSUE THREAD

**Issue by zarpelon** [fireworkweb/fwd#144]
Estou usando o Docker version 19.03.12, build 48a66213fe

E quando tento rodar o fwd start, recebo a mensagem de que o "docker 18 is required"

**Comment by dbpolito** [comment]
Qual versão do `fwd` e `Sistema Operacional` vc está usando?

Roda `fwd --version` pra ver, se não estiver na 1.0.3 roda `fwd self-update` e tenta novamente.

Se o problema persistir envia o `docker info` para tentarmos identificar.

**Comment by fabriciojs** [comment]
@zarpelon boa tarde!

Adicionei um teste com a versão do Docker, e a lógica de validação de versão deveria validar sim 19.03.12.

https://github.com/fireworkweb/fwd/pull/145/files

Você pode fazer o que o @dbpolito indicou acima, além disso por favor:

- Execute o `FWD_VERBOSE=1 fwd start` e pode colar o output aqui.

- Para você trabalhar apesar do problema de validação da versão, você pode fazer `fwd start --no-checks` que vai pular a parte de checks, até ser corrigido.

**Comment by zarpelon** [comment]
Olá! Segue imagem.

![fwd](https://user-images.githubusercontent.com/264762/90762242-1a866b00-e2bb-11ea-9eb3-94952a5c3a12.png)

**Comment by zarpelon** [comment]
![image](https://user-images.githubusercontent.com/264762/90762403-60dbca00-e2bb-11ea-9c31-2861334b5212.png)

**Comment by zarpelon** [comment]
![image](https://user-images.githubusercontent.com/264762/90762574-a39da200-e2bb-11ea-8a90-435b9425e023.png)

**Comment by zarpelon** [comment]
Como eu já tinha os containers criados, eu consigo subir usando o docker start nome1 nome2 , porém não estou conseguindo usando o fwd.

**Comment by fabriciojs** [comment]
The new [kool](https://github.com/kool-dev/kool) has handles newer Docker versions as well as no longer requires docker-compose on the host, using it from a container with known-to-work version..
