### ISSUE TITLE
Adicionar template para criar o docker-compose.yml 

### ISSUE THREAD

**Issue by zarpelon** [fireworkweb/fwd#146]
Pessoal, uma ideia.

Se possível criar um recurso quando eu inicializo o fwd em um novo projeto. Penso em algo mais ou menos assim, ter um template que monta o **docker-compose.yml** com base em um .sh.

`fwd install --configure `

Abrir um .sh interativo que poderia ter as opções: 

```
Choose your web server [1= apache, 2=nginx, default=nginx]: 
Choose your database [1=mysql, 2=postgres, default=mysql]:
Choose PHP version [1=5.6, 2=7.1, 3=7.2 .... ]:
```
Passado o wizard, poderia salvar esses parâmetros no .fwd e montar o **docker-compose.yml**.

**Comment by fabriciojs** [comment]
@zarpelon obrigado pela issue! Desculpe a demora.

O `fwd` está sendo descontinuado, pois temos trabalhado nos últimos meses muito pesado no nosso novo e melhorado substituto, uma evolução do `fwd` - o Kool https://github.com/kool-dev/kool

Lá a comunidade está totalmente ativa, e nele resolvemos alguns problemas estruturais do `fwd`. Inclusive temos um PR exatamente com esta implementação, que deve entrar na próxima release.

**Comment by zarpelon** [comment]
Beleza @fabriciojs grato pelo feedback.

Vou me incluir nessa também e colaborar com vocês de alguma forma.

Obrigado pelo trabalho e estenda meus parabéns a todos envolvidos.
