### ISSUE TITLE
Add --wait option to fwd start

### ISSUE THREAD

**Issue by dbpolito** [fireworkweb/fwd#31]
Currently we do something like:

```bash
fwd start && sleep 10
```

So there is time for `mysql` to boot, let's add a flag `--wait` that basically holds the command and checks until `mysql` is available.

So if `mysql` boots in 2 seconds it will be faster to run.

A good start would be a `while 1s docker exec mysql select 1=1` just to check when it's booted.

**Comment by fabriciojs** [comment]
This has been accomplished with the new start command.
