### ISSUE TITLE
fwd installation one line script

### ISSUE THREAD

**Issue by dbpolito** [fireworkweb/fwd#4]
Let's write a bash script that can be downloaded and executed in a one-line command that sets up any Laravel project with the latest of our `fwd` environment and CI stack.

**Comment by dbpolito** [comment]
```bash
curl -L "https://raw.githubusercontent.com/fireworkweb/fwd/master/fwd" -o "fwd"
curl -L "https://raw.githubusercontent.com/fireworkweb/fwd/master/docker-compose.yml" -o "docker-compose.yml"
chmod +x fwd
```

```bash
alias fwd="./fwd"
```

**Comment by fabriciojs** [comment]
The installation script must:

- [ ] Be accessible through an URL and piped onto any `bash`.

- [ ] Download the Phar package and but it on a PATH available folder like `/usr/local/bin`.

- [ ] Run `fwd -V` which should either return the properly installed and working version, or error out with missing dependencies (i.e PHP version or extensions).

**Comment by fabriciojs** [comment]
The new [kool](https://github.com/kool-dev/kool) has a very easy one-line installer.
