### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by dbpolito** [fireworkweb/fwd#42]
For now you need to use `Bash for Windows` and add something like this to your `.env`:

```
FWD_CONTEXT_PATH=E:/path
FWD_SSH_KEY_PATH=E:/path
FWD_DOCKER_BIN=docker.exe
FWD_DOCKER_COMPOSE_BIN=docker-compose.exe
FWD_ASUSER=1000
FWD_HTTP_PORT=80
FWD_MYSQL_PORT=3306
FWD_IMAGE_APP=fireworkweb/app:7.2-alpine
FWD_IMAGE_CACHE=redis:alpine
FWD_IMAGE_DATABASE=mysql:5.7
```

**Comment by fabriciojs** [comment]
@felipanico this should go on a section of the README at this point I guess (#13)

**Comment by fabriciojs** [comment]
The tool should use `DIRECTORY_SEPARATOR`, `PHP_EOL` and any other possible OS based constants to help with OS resilience.

**Comment by fabriciojs** [comment]
The new [kool](https://github.com/kool-dev/kool) has support for Windows.
