### ISSUE TITLE
Avoid always running chromedriver

### ISSUE THREAD

**Issue by dbpolito** [fireworkweb/fwd#5]
We don't always want chromedriver to run, we only want it when we are about to run tests.

- [ ] 1. Remove chromedriver from docker-compose.yml

- [ ] 2. Add commands `start:browser` and `stop:browser` that spins up the chromedriver container (detached mode) on the same network as docker-compose.yml containers are running.

- [ ] 3. Consider having a `--wait` option to the `start:browser` command.

- [ ] 4. Consider building the start/stop flow onto the `prepare-dusk` command.

**Comment by fabriciojs** [comment]
@dbpolito updated the description of this. What do you think?

**Comment by fabriciojs** [comment]
The PR https://github.com/fireworkweb/fwd/pull/76 makes this request obsolete. Closing.
