### ISSUE TITLE
Create zsh autocompletions plugin

### ISSUE THREAD

**Issue by gabrielboliveira** [fireworkweb/fwd#52]
We could create a zsh plugin to help autocomplete fwd commands, similar to how `git`, `npm`, `yarn` works.

Eg:

Type `fwd co` and it autocompletes to `fwd composer`. Then tabbing again would suggest all `composer` features, such as install, init, etc

![image](https://user-images.githubusercontent.com/11093090/58039518-64f1c880-7b09-11e9-8d0c-5d2a6f725238.png)

Example for yarn:

![image](https://user-images.githubusercontent.com/11093090/58039544-73d87b00-7b09-11e9-814c-7949615e357f.png)

**Comment by danielsuguimoto** [comment]
https://github.com/stecman/symfony-console-completion

**Comment by fabriciojs** [comment]
The new [kool](https://github.com/kool-dev/kool) solution has shell completion out of the box.
