### ISSUE TITLE
fwd start - Mysql check timeout

### ISSUE THREAD

**Issue by fabriciojs** [fireworkweb/fwd#57]
Mysql times out during `fwd start` even though the container seems to be up and running properly.

**Comment by fabriciojs** [comment]
- [ ] During `Check Docker` on start we must also check for Docker and DockerCompose version.

**Comment by fabriciojs** [comment]
- [ ] Define witch major/minor versions to restrict to on docker and docker-composer; apply the checking to Checking Docker on the start command;

- [ ] Updarte the README to state the known restricted versions

**Comment by fmfernandes** [comment]
If it helps, using `fwd` on bash on Windows, the mysql check times out, when I set `FWD_VERBOSE=true` it shows

```
docker-compose.exe -p project exec -e MYSQL_PWD=secret mysql mysql -u root -e 'SELECT 1'
ERROR: Setting environment for exec is not supported in API < 1.25 (1.22)
```

even tough I'm on `docker-compose version 1.24.0, build 0aa59064`.

When I change the `version` on `docker-compose.yml` from `2` to, say, `3.7` the command works and does not time out, **only** if `FWD_VERBOSE` is true, if set to false the command still times out even when `version` is changed

**Comment by fabriciojs** [comment]
@fmfernandes that is actually a different issue...

Docker Compose version is correct.

That API version though it is something we can change by environment variable, and we do that by setting it up on `.fwd` -  https://github.com/fireworkweb/fwd/blob/php/.fwd#L45

That is how we made it work so far. Maybe there's something different under windows for combination of COMPOSE_API_VERSIOn and actual docker-composer versions.

**Comment by gabrielboliveira** [comment]
We could add a `--skip-checks` to start, so it doesnt perform all those checks. May help

**Comment by fmfernandes** [comment]
That would be useful! 👍

**Comment by fabriciojs** [comment]
Merged a while ago, closing.
