### ISSUE TITLE
Create release candidate distribution channel/flow

### ISSUE THREAD

**Issue by fabriciojs** [fireworkweb/fwd#70]
Figure out how to distribute a main line release and a release candidate in a managed way so users can choose which on they want to use.

**Comment by fabriciojs** [comment]
Release candidate tag: https://github.com/fireworkweb/fwd/releases/tag/v1.0-rc.1

Phar: https://github.com/fireworkweb/fwd/blob/v1.0-rc.1/builds/fwd

**Comment by fabriciojs** [comment]
Installing:

```
curl -L https://github.com/fireworkweb/fwd/blob/v1.0-rc.1/builds/fwd -o /usr/local/bin/fwd
chmod +x /usr/local/bin/fwd
```

**Comment by fabriciojs** [comment]
`v1.0-rc.2` released: https://github.com/fireworkweb/fwd/releases/tag/v1.0-rc.2

**Comment by fabriciojs** [comment]
`v1.0-rc.3` released: https://github.com/fireworkweb/fwd/releases/tag/v1.0-rc.3

**Comment by gabrielboliveira** [comment]
If you need to have both old and RC version, you can do like this:

```
curl -L "https://github.com/fireworkweb/fwd/blob/v1.0-rc.3/builds/fwd?raw=true" -o /usr/local/bin/fwd-1.0
chmod +x /usr/local/bin/fwd-1.0
```

And then just run `fwd-1.0`

**Comment by dbpolito** [comment]
New RC tagged:

```bash
curl -L "https://github.com/fireworkweb/fwd/blob/v1.0-rc.4/builds/fwd?raw=true" -o /usr/local/bin/fwd
chmod +x /usr/local/bin/fwd
```

**Comment by fabriciojs** [comment]
New RC - 5 tagged:

```
curl -L "https://github.com/fireworkweb/fwd/blob/v1.0-rc.5/builds/fwd?raw=true" -o /usr/local/bin/fwd
chmod +x /usr/local/bin/fwd
```

**Comment by fabriciojs** [comment]
The new [kool](https://github.com/kool-dev/kool) has the releases all available right on Github.
