### ISSUE TITLE
Branches organisation

### ISSUE THREAD

**Issue by fabriciojs** [fireworkweb/fwd#90]
Let's decide and apply our strategy for branches organisation, which should start our contributions guidelines.

Suggestion:

- `master`: bleeding-edge, PRs default targets for future Release Candidates.
- `rc-0.0`: The release candidate branch which we should extract from `master` and then PRs could target either the RC or `master` depending on the specifics.
- `v0.0`: the version branch where tags are made against (with minor builds in the end of the tag).

What you guys think? @dbpolito @wesleyhf @gabrielboliveira

**Comment by fabriciojs** [comment]
@gabrielboliveira @dbpolito - let me know if you guys think any different, otherwise I will move ahead with this organisation and document it in a draft of contribution guide.

**Comment by gabrielboliveira** [comment]
I think we don't need a branch for each version, we can use tags for that. But the other two, I agree 👍

**Comment by fabriciojs** [comment]
The argument for having the versions branch is as stated: * with minor builds in the end of the tag*; so we are able to later release two minor patches to two different versions (i.e v1.0.1 and v1.1.1), something like that, as in if we only have the tag pointing to a specific commit we won't have that. 

Of course possibly we won't need or don't want to do that, but that was my original thought.

I can go either way, let's see what @dbpolito thinks.

**Comment by fabriciojs** [comment]
up @gabrielboliveira @dbpolito let's decide and move on with this?
