### ISSUE TITLE
Optional .fwd file on fwd folder

### ISSUE THREAD

**Issue by gabrielboliveira** [fireworkweb/fwd#95]
We already have `.fwd` on project root. We could make it optional to have it on `fwd/.fwd` or `fwd/.env` to be more organized when the project has custom commands/tags

**Comment by fabriciojs** [comment]
@gabrielboliveira so if I understand this correct, you are suggesting we move the `.fwd` file we currently place in a projects root folder to exist within the `fwd/` folder of that project, is that the case?

**Comment by gabrielboliveira** [comment]
@fabriciojs Exactly. For example, if a Laravel project already has custom commands under `fwd/`, we could leave the `.fwd` file on that folder instead of root.

**Comment by fabriciojs** [comment]
I like this. I would suggest the folder to . be `.fwd` actually, just to follow so many other tools related configurations/folders. And that opens up some possibilities I was about to bring up in some other contexts:

```
./
../
.fwd/
   fwd-env-vars
   docker-compose.yml
   .cache/
       .gitignore
       --project-non-versioned-persisted-settings-or-special-data
```

That is a long shot though, which brings in some more complexities (i.e having the default docker-compose load of .env files).

Let's have some more thoughts.

**Comment by gabrielboliveira** [comment]
I like your ideas, @fabriciojs. But let's do step by step 😄 

What you think about first implementing the `.fwd` read from `fwd` folder?

**Comment by fabriciojs** [comment]
> I like your ideas, @fabriciojs. But let's do step by step 😄
> 
> What you think about first implementing the `.fwd` read from `fwd` folder?

That has been accomplished already I believe - check out https://github.com/fireworkweb/fwd/issues/63 and the associated PR #80

**Comment by gabrielboliveira** [comment]
@fabriciojs I meant `fwd` folder inside the project, not `$HOME` 😄

**Comment by fabriciojs** [comment]
> @fabriciojs I meant `fwd` folder inside the project, not `$HOME` 😄

Oh OK, that makes more sense.
