### ISSUE TITLE
Add "logs" command

### ISSUE THREAD

**Issue by gabrielboliveira** [fireworkweb/fwd#97]
Add new `fwd logs` command to show container logs. 

But, should it be just a bypass to `docker-compose logs`, or should we add more info?

**Comment by g0d0** [comment]
## 1. Root path

We should setting logs root path, right?
I read about it on https://laravel-zero.com/docs/logging/#js-nav-menu, "Note on PHAR build" section, BUT ...
I have been thinking about how root path should be setting, and I concluded that saving on `logs` dir on` FWD_CUSTOM_PATH` would be a good place.

Suggestion:

`env ('FWD_CUSTOM_PATH') . DIRECTORY_SEPARATOR . 'logs'`

## 2. Log command

`fwd logs` would return `logs()` laravel helper response.

**Comment by gabrielboliveira** [comment]
@g0d0 Well, I was thinking on just to do a bypass to `docker-compose logs` command and show the containers logs. But you gave an idea: exposing Laravel logs as well.

Eg:

`fwd logs laravel` => show laravel logs
`fwd logs app` => show app container logs
And so on.

We could also have a `-f` option to follow the logs, similar to tail.

**Comment by fabriciojs** [comment]
The new [kool](https://github.com/kool-dev/kool) has this interface with `kool logs`.
